# Generated by Django 5.2 on 2026-01-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
