# Generated by Django 5.2 on 2026-01-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_doctor_nom_doctor_prenom_alter_doctor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('denomination', models.CharField(max_length=255)),
                ('forme', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('cond', models.CharField(max_length=50)),
                ('nom_de_marque', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_nom', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_date', models.DateField()),
                ('docteur_nom', models.CharField(max_length=255)),
                ('docteur_specialite', models.CharField(max_length=100)),
                ('docteur_adresse', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='prescriptions/')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('forme', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('frequence', models.CharField(blank=True, max_length=100, null=True)),
                ('unite_frequence', models.CharField(blank=True, max_length=50, null=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.medicament')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'medicament')},
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicaments',
            field=models.ManyToManyField(through='healthapp.PrescriptionMedicament', to='healthapp.medicament'),
        ),
    ]
